runtime: custom
env: standard
env_variables:
  NEXT_PUBLIC_SANITY_DATASET: production
  NEXT_PUBLIC_SANITY_PROJECT_ID: pnlga7sb
  NEXT_PUBLIC_BASE_URL: http://localhost:3000
  NEXT_PUBLIC_SENDGRID_API_KEY: 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