runtime: nodejs16 # or another supported version

instance_class: F1

handlers:
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /.*
  static_files: build/index.html
  upload: build/index.html

env_variables:
  NEXT_PUBLIC_SANITY_DATASET: production
  NEXT_PUBLIC_SANITY_PROJECT_ID: pnlga7sb
  NEXT_PUBLIC_BASE_URL: http://localhost:3000
  NEXT_PUBLIC_SENDGRID_API_KEY: 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