steps:
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'eu.gcr.io/application:$COMMIT_SHA', '--tag', 'eu.gcr.io/application:latest', '.']
    env:
      - 'NEXT_PUBLIC_KEY=SOME_KEY'
  - id: push
    waitFor: ['build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/application:$COMMIT_SHA']
  - id: push-latest
    waitFor: ['build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/application:latest']
  - id: deploy
    waitFor: ['push']
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'application'
      - '--image'
      - 'eu.gcr.io/application:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'eu.gcr.io/application:$COMMIT_SHA'
options:
  machineType: 'E2_HIGHCPU_8'