steps:
- name: node:17.6.0
  entrypoint: yarn
  args: ["install"]
- name: node:17.6.0
  entrypoint: yarn
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"